### PR TITLE
codemill-id-56e540113fefec0300413b4e fixes #1

### LINKED ISSUE #1: Create a proxy server to act as an API gateway for Anuko Time Tracker
We're using [Anuko Time Tracker](https://www.anuko.com/time_tracker/index.htm) as an organisational time tracker. It's good product but doesn't have an API and therefore we're limited to it's very basic interface. Had we an API we could develop internally some mobile apps to use it, maybe a Slack command, SMS integration, whatever, but there's no API.

So - we want to deploy a node.js server with an API that will act as the client for Anuko Time Tracker. We will execute this node.js proxy server API commands, and it will act as a browser client for the Time Tracker.

Please use express framework.

Please [register a team in their hosted service](https://timetracker.anuko.com/register.php) for development and for being able to understand the detailed requirements: 

The server needs to implement only one method: "track-time". This method will receive login credentials and time tracking parameters, with which you can do a login via [this form](https://timetracker.anuko.com/login.php). And once logged in, it should populate and submit [this form](https://timetracker.anuko.com/time.php) according to the parameters sent.

Please make the server endpoint configurable (we will use our own Anuko installation in production), and the all system deployable to Heroku.

codemill$200

### PR DESCRIPTION
**Pull request by KyleCartmell**
codemill-id-56e540113fefec0300413b4e fixes #1

Deploy to heroku in the usual way.

To track time, post to <base url>/track-time
include Content-Type header set to "application/x-www-form-urlencoded"
body must be a url encoded form containing values:
login - your anuko username
password - your anuko password
project - the name of your anuko project
start - HH:SS start time of the time entry you wish to make
finish - HH:SS finish time of the time entry you wish to make
date - YYYY-MM-DD the date of the time entry you wish to make
note - a descriptive note for your time entry
duration - (optional) overrides the start and finish time and specifies a simple duration for the time entry without a fixed start or finish

Not sure if you're going to want to build a client-side web thing that interacts with this service. If so, adding CORS [is trivial](https://github.com/expressjs/cors#simple-usage-enable-all-cors-requests).

Set environment variable ANUKO_URI to the desired instance of the time tracker. It defaults to the free publicly hosted instance. No trailing slashes, please! (e.g. https://www.my-anuko-instance.com)

### CODE REVIEW

**Comment by KyleCartmell** [comment]
example POST body: login=wakka&password=wakka&project=wakka&start=15%3A11&date=2016-03-15&note=wat&finish=15%3A13

**Comment by shaharsol** [comment]
Hi @KyleCartmell do you have it (or can you have it) running online just so I can test against the default hosted anuko server? it will be much faster for me than to do it myself if you already have one.

**Comment by KyleCartmell** [comment]
https://obscure-mountain-46073.herokuapp.com/track-time

**Comment by shaharsol** [comment]
Cheers @KyleCartmell

**Comment by KyleCartmell** [comment]
1. I saw a message telling me what to do with the PR code so that codemill would recognize it but when I went to actually write up the PR I couldn't find it again so I just put the code everywhere. Some additional docs would help.
2. I got lost in the non-developer mode of the app for a few minutes where it told me my task was missing. Was fairly distressing. As a developer, I don't really care that the other side of the app exists. Maybe make it an opt-in sort of thing?
3. I ended up on the landing page a few times wanting to log in but confused as to how. The call to action for existing users feels a little weak. The github logo in the button is what helped me find my way.
4. Consider minimum offers for tasks. That $7 task with almost no requirements felt bad to even look at. I almost left feedback for the requester but was too annoyed to do so constructively. This task was detailed and greenfield so it felt amazing to be able to sit down and hack it out. Maybe add a tagging system and additional tips for writing up good tasks for those folks? I also would like to receive notifications via email when known, good patrons (like you, for instance) post tasks. I've seen your competitors and haven't used their stuff because it's too much of a bother; you're on to something interesting here and I encourage you to differentiate rather than feature match with existing platforms.
5. I saw a thing in the app that prompted me to fix my ancient PayPal account. But after I did so whatever prompt I ran across could not be found. Another case where additional docs on the Devon side would have eased my mind.
6. The dev UI at old me it was 6pm while I was enjoying my morning coffee. Needs to be made aware of local time?
7. I would have recommended a patch to anuko rather than a gateway API if you were a normal client. Between that and the quite correct feedback from HN. regarding a lack of incentive to test and document I think there is a missing feature here but I'm not certain what it is. Too harsh and it scares away the dev. As a patron I would want some additional carrots to guide developers to do the right thing and avoid PR-time arguments. As a developer, zig I submit the PR and I get a wall of new requirements in response I'm likely to delete the thing and walk away, but I'm going to take it out on codemill since I have no relationship with the taskmaster.
8. Overall, I really like the app and the concept. When it scales I fear the noise to signal ratio and rede to the bottom pricing will push shy me away, just like all the others. But this has promise and my attention. Keep up the good work!

**Comment by shaharsol** [comment]
Thanks @KyleCartmell for truly valuable feedback!

**Pull request merged**
